apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers: 
      - name: backend-pod
        image: darshan616/chat-app-backend
        ports:
        - containerPort: 5001 
        env: 
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: Backend-port
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MONGODB_URI
        - name : JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: JWT_SECRET
  
