apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: chat-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo-pod
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret # It has to the name used in secret metadata! 
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MONGO_INITDB_ROOT_PASSWORD
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db  
      initContainers:
      - name: remove-lock
        image: busybox
        command: ["sh", "-c", "rm -rf /data/db/*"]
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
