apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: chat-app
type: Opaque
data:
  NODE_ENV: "cHJvZHVjdGlvbg=="
  MONGODB_URI: "bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvOjI3MDE3Lz9hdXRoU291cmNlPWFkbWlu"
  JWT_SECRET: "ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjME16ZzNPVEV6TlN3aWFXRjBJam94TnpRek9EYzVNVE0xZlEuNkZUd0FSNTNxYVdQTDRzOVhjTnphd2x4eFpiMGhQcmU5a1lzVml2VHJiOA=="
  MONGO_INITDB_ROOT_USERNAME: "bW9uZ29hZG1pbg=="
  MONGO_INITDB_ROOT_PASSWORD: "c2VjcmV0"
